defaultTime: 300
RedPosition: "504 4 233"
BluePosition: "404 4 165"
LobbyPosition: "449 39 140"
ArrowRange: 2
canRespawn: true
notBrokenBlocks:
  - 
  - 
  - 
  - 
beginCoordinate: "399 4 161"
stageName: 