name: "${project.name}"
version: "${project.version}"
main: "${project.groupId}.Main"
author: 'erudo'
depend: [WorldEdit]
commands:
   ebs:
    description: ebowspleef command
permissions:
  ebs.commands.start:
    default: op
  ebs.commands.set:
    default: op
  ebs.commands.setred:
    default: op
  ebs.commands.setblue:
    default: op
  ebs.commands.redpos:
    default: op
  ebs.commands.bluepos:
    default: op
  ebs.commands.lobbypos:
    default: op
  ebs.commands.shopper:
    default: op
  ebs.commands.version:
    default: true